//! shellcode.rs — AES-256 key and GCM nonce
//!
//! This file is auto-generated by prepare.sh — do not edit by hand.
//!
//!   ./prepare.sh -i beacon.bin [-o output_name]
//!
//! KEY and NONCE are replaced with fresh random values on every prepare.sh
//! run. The encrypted payload is embedded via include_bytes!("payload.bin")
//! in crypto.rs — src/payload.bin is written and cleaned up by prepare.sh.

/// 32-byte AES-256 key — generated at build time by prepare.sh.
pub const KEY: [u8; 32] = [0u8; 32];

/// 12-byte GCM nonce — generated at build time by prepare.sh.
pub const NONCE: [u8; 12] = [0u8; 12];
