//! shellcode.rs — encrypted payload blob and shared key material
//!
//! This file is auto-generated by prepare.sh — do not edit by hand.
//!
//!   ./prepare.sh -i beacon.bin [-o output_name]
//!
//! KEY, NONCE, and ENCRYPTED_SHELLCODE are replaced with fresh random
//! values on every prepare.sh run.

/// 32-byte AES-256 key — generated at build time by prepare.sh.
pub const KEY: [u8; 32] = [0u8; 32];

/// 12-byte GCM nonce — generated at build time by prepare.sh.
pub const NONCE: [u8; 12] = [0u8; 12];

/// AES-256-GCM encrypted shellcode — generated at build time by prepare.sh.
pub const ENCRYPTED_SHELLCODE: [u8; 16] = [0u8; 16];
